# Generated by Django 2.2.7 on 2019-11-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='anyversary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='birthday',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='celebrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='general',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='houses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='worker',
            field=models.FloatField(default=0.0),
        ),
    ]
