# Generated by Django 2.2.7 on 2019-11-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_item_common_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('likes', models.IntegerField(default=0)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.Item')),
            ],
        ),
    ]
