# Generated by Django 2.2.7 on 2019-11-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
