# Generated by Django 2.2.7 on 2019-11-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='anyversary',
            new_name='anniversary',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='artist',
            new_name='jobless',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='student',
            new_name='teenager',
        ),
        migrations.AddField(
            model_name='item',
            name='university_student',
            field=models.FloatField(default=0.0),
        ),
    ]
