# Generated by Django 2.2.7 on 2019-11-09 18:11

from django.db import migrations, models
import recommend.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_auto_20191109_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to=recommend.models.user_path),
        ),
    ]
